services:
  - type: web
    name: comunisolve
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_SSL
        value: true
      - key: APP_URL
        value: https://comunisolve.onrender.com
    healthCheckPath: /
    autoDeploy: true